# Generated by Django 5.0.4 on 2024-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML_Application', '0002_remove_user_first_name_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='hamza', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='ait youssef', max_length=50),
            preserve_default=False,
        ),
    ]
